### ISSUE TITLE
APHA Abstract

### ISSUE THREAD

**Issue by ghost** [Twitter-R01/TwitterR01#3]
Need to create 250 word long abstract detailing progress made with BERTweet over the original LSTM classifier for APHA. 
https://www.apha.org/Events-and-Meetings/APHA-Calendar/2021/2021-APHA-Annual-Meeting-and-Expo

Due - March 21

@wbaker23 Please comment the apha links from the group meeting on 3/11/2021

**Comment by wbaker23** [comment]
14:35:08 From  Justin Zhan  to  Everyone : https://publichealth.jmir.org/
14:36:22 From  Brian Primack  to  Everyone : https://www.apha.org/Events-and-Meetings/APHA-Calendar/2021/2021-APHA-Annual-Meeting-and-Expo
14:36:36 From  Alex Russell  to  Everyone : Abstracts are due March 21
14:38:31 From  Alex Russell  to  Everyone : There's an "Applied Public Health Statistics" section....
14:38:51 From  Alex Russell  to  Everyone : it encompasses "big data and machine learning for health research"
14:40:51 From  Justin Zhan  to  Everyone : https://www.jmir.org/
14:41:12 From  Alex Russell  to  Everyone : Abstracts are 250 word max for that section btw
14:43:10 From  Alex Russell  to  Everyone : https://apha.confex.com/apha/2021/aphs.htm

**Comment by ghost** [comment]
Link to overleaf: https://www.overleaf.com/9159188391xmqftfmrzcvp

**Comment by ghost** [comment]
Submitted to the APHA conference. Thanks for all the help @colditzjb !
